### ISSUE TITLE
FHIR Header Datatype Mapping Error

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#100]
Runtime log:

[ERROR] Failed executing Executing mapFHIR_PeriodToDateTime := No such function mapFHIR_PeriodToDateTime
[ERROR] No such function mapFHIR_PeriodToDateTime
java.lang.NoSuchMethodException: No such function mapFHIR_PeriodToDateTime
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:204)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
	at org.mdmi.core.engine.DatamapInterpreter.execute(DatamapInterpreter.java:228)
	at org.mdmi.core.engine.ConversionImpl.execSrcRule(ConversionImpl.java:185)
	at org.mdmi.core.engine.ConversionImpl.convert(ConversionImpl.java:139)
	at org.mdmi.core.engine.MdmiUow.processConversions(MdmiUow.java:583)
	at org.mdmi.core.engine.MdmiUow.run(MdmiUow.java:899)
	at org.mdmi.core.engine.MdmiEngine.executeTransfer(MdmiEngine.java:94)
	at org.mdmi.core.Mdmi.executeTransfer(Mdmi.java:461)
	at org.mdmi.core.runtime.RuntimeService.runTransformationISO(RuntimeService.java:126)
	at org.mdmi.core.runtime.RuntimeServiceISOMain.main(RuntimeServiceISOMain.java:51)
[ERROR] DATATYPE MISMATCH FOR BUSINESS ELEMENT DocumentServiceEventStartDateTime

**Comment by mryanlord** [comment]
obe
