### ISSUE TITLE
No transformation with eLTSS or Riverside, Partners as source

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#124]
No blow up, but nothing parsed or serialized. 

I think it is because all the .mdmi maps have the same MessageGroup.ModelName - "MessageGroup.ModelName"

Maps attached
[NoParseSerialize4.27.zip](https://github.com/MDMI/mdmiecore/files/1955399/NoParseSerialize4.27.zip)

Tried changing this and got an error:

DEBUG] Loaded message group MessageGroup
[DEBUG] Loaded message model MessageGroup.CPassignment
[ERROR] cant find MessageGroup.eLTSSModel
org.mdmi.core.MdmiException: Cannot resolve reference model MessageGroup.eLTSSModel
	at org.mdmi.core.MdmiModelRef.resolve(MdmiModelRef.java:139)
	at org.mdmi.core.MdmiModelRef.getModel(MdmiModelRef.java:102)
	at org.mdmi.core.runtime.RuntimeService.runTransformation(RuntimeService.java:86)
	at org.mdmi.core.runtime.RuntimeServiceMain.main(RuntimeServiceMain.java:55)
Exception in thread "main" java.lang.AssertionError: Cannot resolve reference model MessageGroup.eLTSSModel
	at org.junit.Assert.fail(Assert.java:88)
	at org.mdmi.core.runtime.RuntimeServiceMain.main(RuntimeServiceMain.java:68)

**Comment by mryanlord** [comment]
OBE
