### ISSUE TITLE
Exception from Apostrophe (Open Quote) In Name

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#148]
Runtime throws an error for names like O'Lord. Maps and message attached, error below

[ERROR] Error executing rule 
javax.script.ScriptException: <eval>:4:51 Missing close quote
value.getXValue().addValue('family',  '<O'Lord'  );
                                                   ^ in <eval> at line number 4 at column number 51
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:537)
	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:524)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(Unknown Source)
	at org.mdmi.core.engine.JsAdapter.eval(JsAdapter.java:123)
	at org.mdmi.core.engine.JsAdapter.evalAction(JsAdapter.java:88)
	at org.mdmi.core.engine.DefaultSemanticParser.evalRule(DefaultSemanticParser.java:1263)
	at org.mdmi.core.engine.DefaultSemanticParser.setComputedValue(DefaultSemanticParser.java:1081)
	at org.mdmi.core.engine.DefaultSemanticParser.buildSemanticModel(DefaultSemanticParser.java:90)
	at org.mdmi.core.engine.MdmiUow.processInboundSourceMessage(MdmiUow.java:304)
	at org.mdmi.core.engine.MdmiUow.run(MdmiUow.java:170)
	at org.mdmi.core.engine.MdmiEngine.executeTransfer(MdmiEngine.java:79)
	at org.mdmi.core.Mdmi.exec(Mdmi.java:382)
	at org.mdmi.core.Mdmi.executeTransfer(Mdmi.java:276)
	at org.mdmi.core.runtime.RuntimeService.runTransformation(RuntimeService.java:97)
	at org.mdmi.core.runtime.RuntimeServiceMain.main(RuntimeServiceMain.java:133)
Caused by: jdk.nashorn.internal.runtime.ParserException: <eval>:4:51 Missing close quote
value.getXValue().addValue('family',  '<O'Lord'  );
                                                   ^
	at jdk.nashorn.internal.parser.Lexer.error(Lexer.java:1700)
	at jdk.nashorn.internal.parser.Lexer.scanString(Lexer.java:988)
	at jdk.nashorn.internal.parser.Lexer.lexify(Lexer.java:1611)
	at jdk.nashorn.internal.parser.AbstractParser.getToken(AbstractParser.java:132)
	at jdk.nashorn.internal.parser.AbstractParser.nextToken(AbstractParser.java:213)
	at jdk.nashorn.internal.parser.AbstractParser.nextOrEOL(AbstractParser.java:170)
	at jdk.nashorn.internal.parser.AbstractParser.next(AbstractParser.java:157)
	at jdk.nashorn.internal.parser.Parser.parse(Parser.java:281)
	at jdk.nashorn.internal.parser.Parser.parse(Parser.java:249)
	at jdk.nashorn.internal.runtime.Context.compile(Context.java:1284)
	at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:1251)
	at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:627)
	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:535)
	... 16 more
[ERROR] Exception during transformation
org.mdmi.core.MdmiException: evalAction(SemanticElement: PatientNameRollup
  parent: TuftsUpdateFile [struct...]

, value.getXValue().addValue('family',  '<O'Lord'  );) fails!
	at org.mdmi.core.engine.JsAdapter.evalAction(JsAdapter.java:90)
	at org.mdmi.core.engine.DefaultSemanticParser.evalRule(DefaultSemanticParser.java:1263)
	at org.mdmi.core.engine.DefaultSemanticParser.setComputedValue(DefaultSemanticParser.java:1081)
	at org.mdmi.core.engine.DefaultSemanticParser.buildSemanticModel(DefaultSemanticParser.java:90)
	at org.mdmi.core.engine.MdmiUow.processInboundSourceMessage(MdmiUow.java:304)
	at org.mdmi.core.engine.MdmiUow.run(MdmiUow.java:170)
	at org.mdmi.core.engine.MdmiEngine.executeTransfer(MdmiEngine.java:79)
	at org.mdmi.core.Mdmi.exec(Mdmi.java:382)
	at org.mdmi.core.Mdmi.executeTransfer(Mdmi.java:276)
	at org.mdmi.core.runtime.RuntimeService.runTransformation(RuntimeService.java:97)
	at org.mdmi.core.runtime.RuntimeServiceMain.main(RuntimeServiceMain.java:133)
Caused by: javax.script.ScriptException: <eval>:4:51 Missing close quote
value.getXValue().addValue('family',  '<O'Lord'  );
                                                   ^ in <eval> at line number 4 at column number 51
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:537)
	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:524)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(Unknown Source)
	at org.mdmi.core.engine.JsAdapter.eval(JsAdapter.java:123)
	at org.mdmi.core.engine.JsAdapter.evalAction(JsAdapter.java:88)
	... 10 more
Caused by: jdk.nashorn.internal.runtime.ParserException: <eval>:4:51 Missing close quote
value.getXValue().addValue('family',  '<O'Lord'  );
                                                   ^
	at jdk.nashorn.internal.parser.Lexer.error(Lexer.java:1700)
	at jdk.nashorn.internal.parser.Lexer.scanString(Lexer.java:988)
	at jdk.nashorn.internal.parser.Lexer.lexify(Lexer.java:1611)
	at jdk.nashorn.internal.parser.AbstractParser.getToken(AbstractParser.java:132)
	at jdk.nashorn.internal.parser.AbstractParser.nextToken(AbstractParser.java:213)
	at jdk.nashorn.internal.parser.AbstractParser.nextOrEOL(AbstractParser.java:170)
	at jdk.nashorn.internal.parser.AbstractParser.next(AbstractParser.java:157)
	at jdk.nashorn.internal.parser.Parser.parse(Parser.java:281)
	at jdk.nashorn.internal.parser.Parser.parse(Parser.java:249)
	at jdk.nashorn.internal.runtime.Context.compile(Context.java:1284)
	at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:1251)
	at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:627)
	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:535)
	... 16 more
[TRACE] 
[ApostropheInName.zip](https://github.com/MDMI/mdmiecore/files/2209875/ApostropheInName.zip)

**Comment by swmuir** [comment]
Fixed
