### ISSUE TITLE
EffectiveTime mappings failing in CCD

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#211]
Some datatype issues regarding CDA date and time datatypes are causing .mdmi transform failures. Using continuityofcaredocument.mdmi map, updated in git. During ISO testing, this error appears:

[TRACE] convert business element ProcedureMedicationEndDateTime
[TRACE] Executing Method mapTSToDateTime
[ERROR] Failed executing Executing mapTSToDateTime := No such function mapTSToDateTime
[ERROR] No such function mapTSToDateTime
java.lang.NoSuchMethodException: No such function mapTSToDateTime
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:204)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
	at org.mdmi.core.engine.DatamapInterpreter.execute(DatamapInterpreter.java:255)
	at org.mdmi.core.engine.ConversionImpl.execMapToMDMI(ConversionImpl.java:259)
	at org.mdmi.core.engine.ConversionImpl.convert(ConversionImpl.java:150)
	at org.mdmi.core.engine.MdmiUow.processConversions(MdmiUow.java:505)
	at org.mdmi.core.engine.MdmiUow.run(MdmiUow.java:1003)
	at org.mdmi.core.engine.MdmiEngine.executeTransfer(MdmiEngine.java:94)
	at org.mdmi.core.Mdmi.executeTransfer(Mdmi.java:496)
	at org.mdmi.core.runtime.RuntimeService.runTransformationISO(RuntimeService.java:149)
	at org.mdmi.core.runtime.RuntimeServiceISOMain.main(RuntimeServiceISOMain.java:51)
[ERROR] DATATYPE MISMATCH FOR BUSINESS ELEMENT ProcedureMedicationEndDateTime

**Comment by mryanlord** [comment]
Seems like is may just be missing a datatype mapping TSToDateTime? I don't see it in that map. Maybe it got fat fingered out by one of us?

**Comment by swmuir** [comment]
Pushed a fix - do a check for updates 

Need to work on date processing in general

**Comment by mryanlord** [comment]
Times coming across. Fixed
