### ISSUE TITLE
Telecom Datatype Mapping Kicks exception

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#223]
Trying to get Patient telecom to transform, finally generated an error to fix:

[ERROR] Failed executing Executing mapTELToTelecom := TypeError: null has no such function "startsWith" in <eval> at line number 95
[ERROR] TypeError: null has no such function "startsWith" in <eval> at line number 95
javax.script.ScriptException: TypeError: null has no such function "startsWith" in <eval> at line number 95
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
	at org.mdmi.core.engine.DatamapInterpreter.execute(DatamapInterpreter.java:255)
	at org.mdmi.core.engine.ConversionImpl.execMapToMDMI(ConversionImpl.java:262)
	at org.mdmi.core.engine.ConversionImpl.convert(ConversionImpl.java:150)
	at org.mdmi.core.engine.MdmiUow.processConversions(MdmiUow.java:505)
	at org.mdmi.core.engine.MdmiUow.run(MdmiUow.java:166)
	at org.mdmi.core.engine.MdmiEngine.executeTransfer(MdmiEngine.java:79)
	at org.mdmi.core.Mdmi.exec(Mdmi.java:395)
	at org.mdmi.core.Mdmi.executeTransfer(Mdmi.java:289)
	at org.mdmi.core.runtime.RuntimeService.runTransformation(RuntimeService.java:99)
	at org.mdmi.core.runtime.RuntimeServiceMain.main(RuntimeServiceMain.java:143)
Caused by: <eval>:95 TypeError: null has no such function "startsWith"
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
	at jdk.nashorn.internal.runtime.linker.NashornBottomLinker.linkNull(NashornBottomLinker.java:180)
	at jdk.nashorn.internal.runtime.linker.NashornBottomLinker.getGuardedInvocation(NashornBottomLinker.java:66)
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154)
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253)
	at jdk.nashorn.internal.scripts.Script$Recompilation$18$3288AA$\^eval\_.mapTELToTelecom(<eval>:95)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:661)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
	... 11 more
[ERROR] DATATYPE MISMATCH FOR BUSINESS ELEMENT PatientPhoneContact

**Comment by swmuir** [comment]
NPE solved
