### ISSUE TITLE
V2 Pipe Hat to XML Broken

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#249]
Recently parser was working for all attached 
[PipeHatParser.zip](https://github.com/MDMI/mdmiecore/files/3750995/PipeHatParser.zip)
messages, now getting exception.
Getting exception during transformation:
[ERROR] Syntax.parse(): unexpected exception
[Fatal Error] :1:1: Content is not allowed in prolog.
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
	at org.mdmi.core.engine.xml.DOMSAXSyntacticParser.saxParse(DOMSAXSyntacticParser.java:943)
	at org.mdmi.core.engine.xml.DOMSAXSyntacticParser.parse(DOMSAXSyntacticParser.java:994)
	at org.mdmi.core.engine.MdmiUow.processInboundSourceMessage(MdmiUow.java:320)
	at org.mdmi.core.engine.MdmiUow.run(MdmiUow.java:174)
	at org.mdmi.core.engine.MdmiEngine.executeTransfer(MdmiEngine.java:79)
	at org.mdmi.core.Mdmi.exec(Mdmi.java:426)
	at org.mdmi.core.Mdmi.executeTransfer(Mdmi.java:319)
	at org.mdmi.core.runtime.RuntimeService.runTransformation(RuntimeService.java:116)
	at org.mdmi.core.runtime.RuntimeServiceMain.main(RuntimeServiceMain.java:143)
[ERROR] Exception during transformation
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)

**Comment by mryanlord** [comment]
issue resolved with new build
