### ISSUE TITLE
Runtime unable to read xmi direct stream

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#30]
[foodsample.zip](https://github.com/MDMI/mdmiecore/files/1218884/foodsample.zip)
Unable to read XMI direct stream.  Is the XML Reader positioned correctly?

Error: java.lang.IllegalStateException
Message: Unable to read XMI direct stream.  Is the XML Reader positioned correctly?

java.lang.IllegalStateException: Unable to read XMI direct stream.  Is the XML Reader positioned correctly?
	at org.openhealthtools.mdht.mdmi.model.xmi.direct.reader.XMIReaderSimple.validatePosition(XMIReaderSimple.java:71)
	at org.openhealthtools.mdht.mdmi.model.xmi.direct.reader.XMIReaderDirectAbstract.readAndBuild(XMIReaderDirectAbstract.java:45)
	at org.openhealthtools.mdht.mdmi.model.xmi.direct.reader.MapBuilderXMIDirect.build(MapBuilderXMIDirect.java:140)
	at org.openhealthtools.mdht.mdmi.MdmiResolver.resolveOne(MdmiResolver.java:166)
	at org.openhealthtools.mdht.mdmi.testui.FrmMain.setSourceMap(FrmMain.java:405)
	at org.openhealthtools.mdht.mdmi.testui.FrmMain.setSourceMap(FrmMain.java:388)
	at org.openhealthtools.mdht.mdmi.testui.FrmMain.onSelSourceMap(FrmMain.java:217)
	at org.openhealthtools.mdht.mdmi.testui.FrmMain$2.actionPerformed(FrmMain.java:667)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
[foodsample.zip](https://github.com/MDMI/mdmiecore/files/1218660/foodsample.zip)

**Comment by swmuir** [comment]
Food sample creates a MDMI model

**Comment by mryanlord** [comment]
new issue created for missing xml values
