### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 

### ISSUE THREAD

**Issue by swmuir** [MDMI/mdmiecore#41]
qvto:transformation] java.lang.ArrayIndexOutOfBoundsException: 0
[qvto:transformation]  at org.eclipse.mdht.uml.cda.core.util.CDAModelUtil.transformToCDAProperty(CDAModelUtil.java:1211)
[qvto:transformation]  at org.eclipse.mdht.uml.cda.core.util.CDAModelUtil.getCDAProperty(CDAModelUtil.java:151)
[qvto:transformation]  at org.eclipse.mdht.uml.cda.core.util.CDACommonUtils.getCDAProperty(CDACommonUtils.java:858)
[qvto:transformation]  at org.eclipse.mdht.uml.cda.core.util.CDACommonUtils.getCDAProperty(CDACommonUtils.java:890)
[qvto:transformation]  at org.mdmi.qvt.cda.blackbox.CdaLibrary.getMDMIDatype(CdaLibrary.java:1042)

**Comment by swmuir** [comment]
Fixed
