### ISSUE TITLE
Runtime error in loading CDAmap

### ISSUE THREAD

**Issue by KenLord** [MDMI/mdmiecore#57]
on 10/19, I attempted to load the file cdamap.xmi into the current version of the runtime as the source message. I got the  error below message. Also, I do get an error on my machine when I do the cda transform application but it does create the .xmi file.                                                                                                                                       

Error: java.lang.reflect.UndeclaredThrowableException
Message: null

Caused by:
Error: java.lang.reflect.InvocationTargetException
Message: null

Caused by:
Error: javax.xml.stream.XMLStreamException
Message: ParseError at [row,col]:[34968,64]
Message: The value of attribute "xmi:idref" associated with an element type "businessElement" must not contain the '<' character.

java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy3.next(Unknown Source)
	at org.openhealthtools.mdht.mdmi.model.xmi.direct.reader.XMIReaderSimple.advanceToNextChildElement(XMIReaderSimple.java:80)
	at org.openhealthtools.mdht.mdmi.model.xmi.direct.reader.XMIReaderDirectAbstract.readAndBuild(XMIReaderDirectAbstract.java:63)
	at org.openhealthtools.mdht.mdmi.model.xmi.direct.reader.SemanticElementReader.readSingleChildElement(SemanticElementReader.java:86)
	at org.openhealthtools.mdht.mdmi.model.xmi.direct.reader.SemanticElementReader.readSingleChildElement(SemanticElementReader.java:33)
	at org.openhealthtools.mdht.mdmi.model.xmi.direct.reader.XMIReaderDirectAbstract.readAndBuild(XMIReaderDirectAbstract.java:79)
	at org.openhealthtools.mdht.mdmi.model.xmi.direct.reader.SemanticElementSetReader.readSingleChildElement(SemanticElementSetReader.java:56)
	at org.openhealthtools.mdht.mdmi.model.xmi.direct.reader.SemanticElementSetReader.readSingleChildElement(SemanticElementSetReader.java:29)
	at org.openhealthtools.mdht.mdmi.model.xmi.direct.reader.XMIReaderDirectAbstract.readAndBuild(XMIReaderDirectAbstract.java:79)
	at org.openhealthtools.mdht.mdmi.model.xmi.direct.reader.MessageModelReader.readSingleChildElement(MessageModelReader.java:54)
	at org.openhealthtools.mdht.mdmi.model.xmi.direct.reader.MessageModelReader.readSingleChildElement(MessageModelReader.java:29)
	at org.openhealthtools.mdht.mdmi.model.xmi.direct.reader.XMIReaderDirectAbstract.readAndBuild(XMIReaderDirectAbstract.java:79)
	at org.openhealthtools.mdht.mdmi.model.xmi.direct.reader.MessageGroupReader.readSingleChildElement(MessageGroupReader.java:79)
	at org.openhealthtools.mdht.mdmi.model.xmi.direct.reader.MessageGroupReader.readSingleChildElement(MessageGroupReader.java:37)
	at org.openhealthtools.mdht.mdmi.model.xmi.direct.reader.XMIReaderDirectAbstract.readAndBuild(XMIReaderDirectAbstract.java:79)
	at org.openhealthtools.mdht.mdmi.model.xmi.direct.reader.XMIRootReaderDirect.readSingleChildElement(XMIRootReaderDirect.java:57)
	at org.openhealthtools.mdht.mdmi.model.xmi.direct.reader.XMIRootReaderDirect.readSingleChildElement(XMIRootReaderDirect.java:28)
	at org.openhealthtools.mdht.mdmi.model.xmi.direct.reader.XMIReaderDirectAbstract.readAndBuild(XMIReaderDirectAbstract.java:79)
	at org.openhealthtools.mdht.mdmi.model.xmi.direct.reader.MapBuilderXMIDirect.build(MapBuilderXMIDirect.java:140)
	at org.openhealthtools.mdht.mdmi.MdmiResolver.resolveOne(MdmiResolver.java:158)
	at org.openhealthtools.mdht.mdmi.testui.FrmMain.setSourceMap(FrmMain.java:407)
	at org.openhealthtools.mdht.mdmi.testui.FrmMain.setSourceMap(FrmMain.java:384)
	at org.openhealthtools.mdht.mdmi.testui.FrmMain.onSelSourceMap(FrmMain.java:217)
	at org.openhealthtools.mdht.mdmi.testui.FrmMain$2.actionPerformed(FrmMain.java:669)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.openhealthtools.mdht.mdmi.model.xmi.direct.reader.XMLStreamReaderProxy.invoke(XMLStreamReaderProxy.java:40)
	... 61 more
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[34968,64]
Message: The value of attribute "xmi:idref" associated with an element type "businessElement" must not contain the '<' character.
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(Unknown Source)
	... 65 more

**Comment by KenLord** [comment]
this is the xmi file generated. I have changed the file type to docx because this is the only way I can attach it
[cdamap - Copy.docx](https://github.com/MDMI/mdmiecore/files/1402070/cdamap.-.Copy.docx)

**Comment by swmuir** [comment]
Save as or transform did not complete;  How was the xmi file created ?

**Comment by KenLord** [comment]
i used the fhirtransform app on the consol model (from the green triangle
dropdown).

**Comment by KenLord** [comment]
in eclipse, i used the fhirtransform app on the consol uml model (via the
green triangle dropdown).

**Comment by swmuir** [comment]
Updated transform and removed automated export to XMI 
To test - Rerun transform; open MDMI file; use the file save as option to create new XMI file

There was a choice group in the CDA MDMI file which the local CDA export missed - removing local export and using the save as centralizes the export logic if other issues are found

**Comment by KenLord** [comment]
Closed. Downloaded updates, reran CDA transform. Load xmi into runtime and ran isomorphically using TOC sample message.  Transform ran without error. Will investigate details of transform later.
