### ISSUE TITLE
FHIR Immunizations ISO - FAIL

### ISSUE THREAD

**Issue by swmuir** [MDMI/mdmiecore#87]
valus is Section_slice_pos12.Name73.family.value.ImmunizationAdministeredPerformerName
valus is Section_slice_pos12.Name73.given.value.ImmunizationAdministeredPerformerName
valus is Section_slice_pos12.Name73.suffix.value.ImmunizationAdministeredPerformerName
valus is Section_slice_pos12.Name73.prefix.value.ImmunizationAdministeredPerformerName
[INFO] Execute processOutboundTargetMessage
[ERROR] Invalid map: expected XDataStruct for node value : Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11369-6']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-immunization']/performer/telecom/valueSection_slice_pos12.Telecom57.value.value.ImmunizationAdministeredPerformerOrganizationTelecom
[ERROR] Invalid map: expected XDataStruct for node use : Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11369-6']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-immunization']/performer/telecom/useSection_slice_pos12.Telecom57.use.value.ImmunizationAdministeredPerformerOrganizationTelecom
[ERROR] Invalid map: expected XDataStruct for node use : Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11369-6']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-immunization']/performer/telecom/useSection_slice_pos12.Telecom57.use.value.ImmunizationAdministeredPerformerOrganizationTelecom
java.lang.NumberFormatException
	at java.math.BigDecimal.<init>(BigDecimal.java:550)
	at java.math.BigDecimal.<init>(BigDecimal.java:383)
	at java.math.BigDecimal.<init>(BigDecimal.java:806)
	at org.mdmi.core.engine.converter.from.BigDecimalConverter.convertFromString(BigDecimalConverter.java:22)
	at org.mdmi.core.engine.XDT.convertFromString(XDT.java:190)
	at org.mdmi.core.engine.DefaultSemanticParser.getValueLeaf(DefaultSemanticParser.java:410)
	at org.mdmi.core.engine.DefaultSemanticParser.getValue(DefaultSemanticParser.java:378)
	at org.mdmi.core.engine.DefaultSemanticParser.getValueStruct(DefaultSemanticParser.java:495)
	at org.mdmi.core.engine.DefaultSemanticParser.getValue(DefaultSemanticParser.java:382)
	at org.mdmi.core.engine.DefaultSemanticParser.getStructElement(DefaultSemanticParser.java:362)
	at org.mdmi.core.engine.DefaultSemanticParser.getMappedElement(DefaultSemanticParser.java:197)
	at org.mdmi.core.engine.DefaultSemanticParser.getStructElement(DefaultSemanticParser.java:311)
	at org.mdmi.core.engine.DefaultSemanticParser.getMappedElement(DefaultSemanticParser.java:197)
	at org.mdmi.core.engine.DefaultSemanticParser.getStructElement(DefaultSemanticParser.java:311)
	at org.mdmi.core.engine.DefaultSemanticParser.getMappedElement(DefaultSemanticParser.java:197)
	at org.mdmi.core.engine.DefaultSemanticParser.getStructElement(DefaultSemanticParser.java:311)
	at org.mdmi.core.engine.DefaultSemanticParser.getMappedElement(DefaultSemanticParser.java:197)
	at org.mdmi.core.engine.DefaultSemanticParser.getStructElement(DefaultSemanticParser.java:311)
	at org.mdmi.core.engine.DefaultSemanticParser.getMappedElement(DefaultSemanticParser.java:197)
	at org.mdmi.core.engine.DefaultSemanticParser.getElements(DefaultSemanticParser.java:187)
	at org.mdmi.core.engine.DefaultSemanticParser.buildSemanticModel(DefaultSemanticParser.java:73)
	at org.mdmi.core.engine.MdmiUow.processInboundSourceMessage(MdmiUow.java:372)
	at org.mdmi.core.engine.MdmiUow.run(MdmiUow.java:945)
	at org.mdmi.core.engine.MdmiEngine.executeTransfer(MdmiEngine.java:94)
	at org.mdmi.core.Mdmi.executeTransfer(Mdmi.java:461)
	at org.mdmi.core.runtime.RuntimeService.runTransformationISO(RuntimeService.java:126)

**Comment by swmuir** [comment]
fixed
